### ISSUE TITLE
UseCase: tags for events

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#137]
# UseCase description

This use case is to display a pie chart for profile with tasks grouped by tags. This will allow the user to split event into meaningful groups and see what a given profile is interested to. For example we could tag events such in the following way. Some events are statistical events, some are related to purchase, some are related to marketing.  By grouping events we can see how many purchase events were fired compared to marketing events. 
 

# ToDo

- [x] https://github.com/Tracardi/tracardi/issues/132
- [x] https://github.com/Tracardi/tracardi/issues/131
- [x] https://github.com/Tracardi/tracardi/issues/130
- [x] https://github.com/Tracardi/tracardi/issues/129
- [x] https://github.com/Tracardi/tracardi/issues/136
- [x] https://github.com/Tracardi/tracardi/issues/135
- [x] https://github.com/Tracardi/tracardi/issues/150
- [x] https://github.com/Tracardi/tracardi/issues/154
- [x] #153
- [x] #155
- [x] https://github.com/Tracardi/tracardi-gui/issues/48
- [x] https://github.com/Tracardi/tracardi-gui/issues/49
- [x] #371
