### ISSUE TITLE
Importing workflows from files

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#188]
# Intro

Workflows are just json files and can be imported from file. This task should check if the plugin files are installed/present. And if note mark them as not installed.

# Prerequisites

- [ ] Marking if the plugin files are installed/present.  - It can be a installed flag in plugin metadata.

# Tasks

- [ ] Endpoint to import wrokflow from json file - it can be gzipped and  encoded BASE64
- [ ] Frontend upload form.
