### ISSUE TITLE
FeatureSet: Data schema repository

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#200]
# Intro

Data that are processed in workflows should have data validated on the entry to workflow. We should create a repository of schemas and assign it to event. Then event is assigned to Workflow. Workflow can then use this data to give type hints to dot notation.

# Tasks

- [x] Add index to elastic
- [x] https://github.com/Tracardi/tracardi/issues/254 -  this one is for creating pydantic model
- [x] #269
- [x] Endpoint: List Data schemas (+delete)
- [x] Service: Run validation schema on data
- [x] Endpoint: Add validation schema to event
- [x] Endpoint: Add event type to workflow

# Reference

* Use: https://python-jsonschema.readthedocs.io/en/stable/

**Comment by atompie** [comment]
Congrats this is done.
