### ISSUE TITLE
Add params to workflow

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#508]
Now workflow does not have any configuration. It is a plain name and description. But WF may have parameters that can be used inside WF. We already have a dot notation that can access WF data. 

Now we need a way to add params to WF. 

# Task

- [ ] add config field to WF mapping. It should be of type object and disabled. 

- [ ] On the WF form add group workflow configuration and inside it a JSON field where the user will add conf data. 

- [ ] change WF endpoints to save data from forms to elastic

- [ ] test if you can read this data from dot notation field inside WF
